name: Build and test product service
on:
  push:
    branches:
      - '*'
    paths:
      - 'team-project-group-p8-01/backend/product-ms/**'
jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Wait for MySQL to start
        run: wget -qO- https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh && chmod +x wait-for-it.sh && ./wait-for-it.sh mysql:3306 --timeout=60
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productdb_CI
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpassword
        working-directory: team-project-group-p8-01/backend/product-ms
        run: ./mvnw --batch-mode --update-snapshots package