version: '3.4'
services:
  product:
    platform: "linux/amd64"
    build: backend/product-ms/
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/productdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
      USER_MS_URL: http://user:8081
      NOTIFICATIONS_MS_URL: http://notifications:8083
    depends_on:
      - database
      - delivery
      - user

  delivery:
    platform: "linux/amd64"
    build: backend/delivery-ms/
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/deliverydb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
    depends_on:
        - database

  user:
    platform: "linux/amd64"
    build: backend/user-ms/
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/userdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
    depends_on:
      - database

  notifications:
    platform: "linux/amd64"
    build: backend/notifications-ms/
    ports:
      - "8083:8083"
    
  database:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: accountsdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - "9000:8080"
volumes:
  db: