version: '3.4'
services:
  product:
    platform: "linux/amd64"
    image: 152779307474.dkr.ecr.us-east-1.amazonaws.com/product-ms:latest
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://productdb:3306/productdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
      USER_MS_URL: http://user:8081
      NOTIFICATIONS_MS_URL: http://notifications:8083
    depends_on:
      - productdb
        - delivery
        - user

  delivery:
    platform: "linux/amd64"
    image: 152779307474.dkr.ecr.us-east-1.amazonaws.com/delivery-ms:latest
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://deliverydb:3306/deliverydb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
    depends_on:
      - deliverydb

  user:
    platform: "linux/amd64"
    image: 152779307474.dkr.ecr.us-east-1.amazonaws.com/user-ms:latest
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://userdb:3306/userdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: ${DB_PASSWORD}
    depends_on:
      - userdb

  notifications:
    platform: "linux/amd64"
    image: 152779307474.dkr.ecr.us-east-1.amazonaws.com/notifications-ms:latest
    ports:
      - "8083:8083"

  productdb:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
#    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      #      MYSQL_USER: 'root'
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    #    ports:
    #      - "3307:3306"
    volumes:
      - productdb:/var/lib/mysql

  deliverydb:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
#    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      #      MYSQL_USER: root
      MYSQL_DATABASE: deliverydb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    #    ports:
    #      - "3306:3306"
    volumes:
      - deliverydb:/var/lib/mysql
  userdb:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
#    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    #    ports:
    #      - "3306:3306"
    volumes:
      - userdb:/var/lib/mysql

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - "9000:8080"

volumes:
  productdb:
  deliverydb:
  userdb: