name: CI

on:
  push:
    branches: [ 'ron/DEFECT-backendci' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change to frontend directory
        run: cd frontend

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Test code
        run: cd frontend && npm test

  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ROOT_PASSWORD: 'rootpassword'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
#      - name: Debug MySQL
#        run: docker logs mysql
#      - name: Wait for MySQL to start
#        run: wget -qO- https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh && chmod +x wait-for-it.sh && ./wait-for-it.sh mysql:3306 --timeout=120
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build product-ms
        env:
          SPRING_DATASOURCE_URL: 'jdbc:mysql://localhost:3306/productdb_CI'
          SPRING_DATASOURCE_USERNAME: 'root'
          SPRING_DATASOURCE_PASSWORD: 'rootpassword'
        run: cd backend/product-ms && ./mvnw --batch-mode --update-snapshots package

