name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change to frontend directory
        run: cd frontend

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Test code
        run: cd frontend && npm test

      - name: Use Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test productms
        run: |
          ./backend/product-ms/mvnw --batch-mode --update-snapshots package
          ./backend/product-ms/mvnw --batch-mode test
